"""empty message

Revision ID: 2c9f981c1a6b
Revises: 6343ac0b5485
Create Date: 2016-06-05 22:07:15.169392

"""

# revision identifiers, used by Alembic.
revision = '2c9f981c1a6b'
down_revision = '6343ac0b5485'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
