"""empty message

Revision ID: d1c40731f683
Revises: 75bedda73792
Create Date: 2016-06-02 15:52:11.398590

"""

# revision identifiers, used by Alembic.
revision = 'd1c40731f683'
down_revision = '75bedda73792'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
