"""empty message

Revision ID: dfcd792ccd78
Revises: b57e07001730
Create Date: 2016-05-31 09:45:03.879349

"""

# revision identifiers, used by Alembic.
revision = 'dfcd792ccd78'
down_revision = 'b57e07001730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
